baseURL = 'https://blog.gertm.eu'
languageCode = 'en-us'
title = "Gert's notes"
theme = "ritzy"

[params]
  author = "Gert"
  description = "personal blog"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
